schema: "http://localhost:8080/___graphql"
documents: "src/**/*.{graphql,vue,js,ts}"
extensions:
  codegen:
    generates:
      src/graphql.d.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-graphql-files-modules
