branches:
  only:
    - master

environment:
  NETLIFY_TOKEN:
    secure: Ckk/F/a3H0XY6bKaxg1AzvYWkEL+hOAi+T1CQioS+OMyesd9nze4C4+vDb05m0BY4OBFqahXJsQQdEatTExdmAtlTcovqRPsr9tIg7cWZMQ=

# Temporarily needed until curl added to PATH
# See http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
# And https://github.com/appveyor/ci/issues/1431
install:
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

build_script:
  - ps: .\build.ps1 AppVeyor
