name: Readme updater
on:
  push:
    branches:
      - "main"
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          # feed_list: "https://www.daviddriscoll.me/feed.xml"
          readme_path: ./TEMPLATE.md
          gh_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create README.md
        uses: actions-js/profile-readme@master
        with:
          username: david-driscoll
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}